[package]
name = "video"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"

[build-dependencies]
pkg-config = "0.3.5"
target_build_utils = "0.3"
bindgen = "0.65"
